#! /bin/sh

killall polybar
sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom &
dunst &
polybar -c ~/.config/polybar/config.ini &
xwallpaper --zoom ~/Pictures/marc-marquez-repsol-honda-team-2775092431.jpeg &

bspc monitor -d   %{T2}3%{T-}  %{T2}5%{T-} %{T2}6%{T-} %{T2}7%{T-} %{T2}8%{T-} %{T2}9%{T-} %{T2}10%{T-}

bspc config border_width         2
bspc config window_gap          3

bspc config split_ratio          0.53
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config single_monocle  false
bspc config focused_border_color	 "#ff0000"
bspc config normal_border_color	 "#ffffff"
bspc config top_padding 1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a TopTracker sticky=off

xsetroot -cursor_name left_ptr
